{% set name = "wagtail-modeladmin" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wagtail_modeladmin-{{ version }}.tar.gz
  sha256: a83502b0c02d2376cde33d81eb607ae10be95840b35072404cca877da161f7da

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - wagtail >=5.0

test:
  imports:
    - wagtail_modeladmin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wagtail-nest/wagtail-modeladmin
  summary: Add any model in your project to the Wagtail admin. Formerly wagtail.contrib.modeladmin.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
