{% set name = "wagtail-modeladmin" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wagtail_modeladmin-{{ version }}.tar.gz
  sha256: 41e12f9a79f8c1595fce73bd6b51007422f258089564f9df8e09a82246a8e133

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - wagtail >=5.0
    # - sphinxcontrib-spelling <9.0,>=8.0
    # - sphinx_copybutton >=0.5
    # - sphinx-wagtail-theme ==6.3.0
    # - sphinx-autobuild >=0.6.0
    # - pyenchant <4,>=3.1.1
    # - pre-commit <3.0
    # - myst_parser <1.0,>=0.18.1
    # - dj-database-url >=2.0.0
    # - Wagtail >=5.2
    # - Sphinx >=6.0

test:
  imports:
    - wagtail_modeladmin
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/wagtail-nest/wagtail-modeladmin
  summary: Add any model in your project to the Wagtail admin. Formerly wagtail.contrib.modeladmin.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
